### ISSUE TITLE
Memory leak with Devil?

### ISSUE THREAD

**Issue by mperham** [banister/devil#3]
<pre>
require 'rubygems'
require 'devil'

def memory
  `ps -o vsz,rss -p #{$$}`.strip.split
end

p memory
10.times do
  1_000.times do
    Devil.with_image("a.jpg") do |img|
      # img.thumbnail(100)
      # img.save("a_100.png")
    end
  end
  GC.start
  p Process.times
  p memory
end
</pre>

Just iterating over a with_image block causes the process's RSS to quickly grow.  I'm assuming this is a memory leak.

**Comment by banister** [comment]
close based api implemented in most recent gem
