### ISSUE TITLE
install problem with Macports

### ISSUE THREAD

**Issue by martennilsson** [banister/devil#6]
Hi, tried to install devil on Snow Leopard:

marten@martMBP ~/src/opengl/openglworld$ sudo port install libdevil
dlopen(/opt/local/share/macports/Tcl/pextlib1.0/Pextlib.dylib, 10): no suitable image found.  Did find:
    /opt/local/share/macports/Tcl/pextlib1.0/Pextlib.dylib: mach-o, but wrong architecture
    while executing
"load /opt/local/share/macports/Tcl/pextlib1.0/Pextlib.dylib"
    ("package ifneeded Pextlib 1.0" script)
    invoked from within
"package require Pextlib 1.0"
    (file "/opt/local/bin/port" line 40)

Any ideas?

**Comment by banister** [comment]
Hi, check the following link:
http://trac.macports.org/wiki/Migration

**Comment by banister** [comment]
solved
