### ISSUE TITLE
Documentation: do not recommend install to system32 for Windows

### ISSUE THREAD

**Issue by luislavena** [banister/devil#7]
Hello,

In the documentation page:

http://banisterfiend.wordpress.com/2009/10/14/the-devil-image-library-for-ruby/

You recommend copying DLLs into system32

That practice should be avoided because is not going to be reliable.

system32 requires administrative privileges to copy files inside of it. Under restricted environments, that is not possible.

Also, system32 on a 64bits OS is not actually 32bits, but has been kept for consistency. Instead, 32bits dlls should be placed in SysWOW64 (Windows on Windows emulation layer folder).

I recommend placing these DLLs in the Ruby/bin directory, or other "utility" directory that is not a sensitive as sytem32.

Thank you.

**Comment by banister** [comment]
updated instructions to use c:\ruby\bin\ instead
